### ISSUE TITLE
Upgrading to Youtube API v3.0

### ISSUE THREAD

**Issue by micahgodbolt** [sassbites/sassbit.es#3]
Can't quite tell, but are you using version 2 API to pull in episodes @jshawl ?

**Comment by jshawl** [comment]
It's actually just a public rss link - http://gdata.youtube.com/feeds/api/users/sassbites/uploads

**Comment by micahgodbolt** [comment]
Interesting.....i'm curious what we could do if we actually dove into the v3 API. Something for later then I guess.
